### ISSUE TITLE
Second Screen Clock

### ISSUE THREAD

**Issue by flynnsbit** [jmalarcon/Win11ClockToggler#1]
Any idea how to do this with the second screen clock now that they added it as well?

**Comment by flynnsbit** [comment]
Thank you, works great on primary.  We were looking for something like this for days. I was using ElevenClock and then setting the clock color font to the same color as the task bar.  Super hacky.  Yours is much better!

**Comment by jmalarcon** [comment]
Hi @flynnsbit 

I've added support for secondary screens in the [new version 1.3.0](https://github.com/jmalarcon/Win11ClockToggler/releases/tag/v.1.3.0) 😉

Just use the `--secondary` switch (or `-s`, `/s`) and if will find and hide/show those clocks too.

I'm planning to add a version of the tool with an UI, so that people not used to work with the console can use it easily.

Hope this helps and thanks for the suggestion!

**Comment by flynnsbit** [comment]
Thank you!!
