### ISSUE TITLE
About Windows 11 22H2 v22621.1344

### ISSUE THREAD

**Issue by jzeb** [jmalarcon/Win11ClockToggler#23]
Hello, your software is very good, may I ask whether the problem of the task bar under WIN11 has been fixed? Or is there a good solution? Thank you.

**Comment by jmalarcon** [comment]
Hi, please use the community for this kind of things instead of opening an issue. Thank you 😊

Right now, the problem is that, in the way they have designed the new toolbar in 2022H2, if I hide the date/clock, the whole toolbar is hidden. So I don't have any solutions right now except maybe trying to put something like a white rectangle above the clock or something like that. But this goes against the philosophy of this app, which is really hiding the clock.

There are other options around that substitute the clock for a different one (in reality, what they do is overlay something above the real one). For example [ElevenClock](https://github.com/marticliment/ElevenClock). I've not used it myself, but they say it works for changing the look and feel, and I guess you can try to hide the date/clock with it.

Hope this helps.
